package EDCBA;

public enum OperatorType {
    LEFT, RIGHT, ADD, MINUS,
    DOT, COMMA, LOOP_OPEN, LOOP_CLOSE,

    SET_LOCATOR, BRA, METHOD_CALL,
    SET_LOCATOR_Z, SET_LOCATOR_Z_EOF, CALL_Z,

    RET,
    SET_AV, STAR, DOUBLE_QUOTE, BANG, AT_SYMBOL,
    STRING_LITERAL_CHAR, STRING_LITERAL_DOT,

    DEBUG_INSTANT_SAFE_QUIT,

    EOF
}
